In [ ]:
def estimate_auto_mpg(model year, horsepower)
#assume all mpg are worth at least 8
value=8
#asjust the value estimate based on the mpg
value=value+()

In [52]:
import pandas as pd
import webbrowser
import os
#read the file
a=pd.read_csv("auto_mpg.csv")

#view the file
html=a[0:].to_html()
with open("anil.html","w") as f:
    f.write(html)

fn=os.path.abspath("anil.html")
webbrowser.open("file://{}".format(fn))

True

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import ensemble
from sklearn.metrics import mean_absolute_error
from sklearn.externals import joblib

#load the file
df=pd.read_csv("auto_mpg.csv")
del df['origin']
del df['weight']
del df['displacement']
del df['acceleration']

#one-hot encoded data
a_df=pd.get_dummies(df, columns=['car name'])

#remove the mpg the data
del a_df['mpg']

#create the x and y arrays
x=a_df.as_matrix()
y=df['mpg'].as_matrix()

x,y

C:\Users\gowri\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
C:\Users\gowri\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

(array([[  0.,   8., 130., ...,   0.,   0.,   0.],
        [  1.,   8., 165., ...,   0.,   0.,   0.],
        [  2.,   8., 150., ...,   0.,   0.,   0.],
        ...,
        [395.,   4.,  84., ...,   0.,   0.,   0.],
        [396.,   4.,  79., ...,   0.,   0.,   0.],
        [397.,   4.,  82., ...,   0.,   0.,   0.]]),
 array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
        14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
        25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
        19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
        13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
        27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
        17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
        22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
        14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
        18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
        22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
        15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
        25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
        26. , 31. , 32. , 28. , 24. , 26. , 24. , 26. , 31. , 19. , 18. ,
        15. , 15. , 16. , 15. , 16. , 14. , 17. , 16. , 15. , 18. , 21. ,
        20. , 13. , 29. , 23. , 20. , 23. , 24. , 25. , 24. , 18. , 29. ,
        19. , 23. , 23. , 22. , 25. , 33. , 28. , 25. , 25. , 26. , 27. ,
        17.5, 16. , 15.5, 14.5, 22. , 22. , 24. , 22.5, 29. , 24.5, 29. ,
        33. , 20. , 18. , 18.5, 17.5, 29.5, 32. , 28. , 26.5, 20. , 13. ,
        19. , 19. , 16.5, 16.5, 13. , 13. , 13. , 31.5, 30. , 36. , 25.5,
        33.5, 17.5, 17. , 15.5, 15. , 17.5, 20.5, 19. , 18.5, 16. , 15.5,
        15.5, 16. , 29. , 24.5, 26. , 25.5, 30.5, 33.5, 30. , 30.5, 22. ,
        21.5, 21.5, 43.1, 36.1, 32.8, 39.4, 36.1, 19.9, 19.4, 20.2, 19.2,
        20.5, 20.2, 25.1, 20.5, 19.4, 20.6, 20.8, 18.6, 18.1, 19.2, 17.7,
        18.1, 17.5, 30. , 27.5, 27.2, 30.9, 21.1, 23.2, 23.8, 23.9, 20.3,
        17. , 21.6, 16.2, 31.5, 29.5, 21.5, 19.8, 22.3, 20.2, 20.6, 17. ,
        17.6, 16.5, 18.2, 16.9, 15.5, 19.2, 18.5, 31.9, 34.1, 35.7, 27.4,
        25.4, 23. , 27.2, 23.9, 34.2, 34.5, 31.8, 37.3, 28.4, 28.8, 26.8,
        33.5, 41.5, 38.1, 32.1, 37.2, 28. , 26.4, 24.3, 19.1, 34.3, 29.8,
        31.3, 37. , 32.2, 46.6, 27.9, 40.8, 44.3, 43.4, 36.4, 30. , 44.6,
        40.9, 33.8, 29.8, 32.7, 23.7, 35. , 23.6, 32.4, 27.2, 26.6, 25.8,
        23.5, 30. , 39.1, 39. , 35.1, 32.3, 37. , 37.7, 34.1, 34.7, 34.4,
        29.9, 33. , 34.5, 33.7, 32.4, 32.9, 31.6, 28.1, 30.7, 25.4, 24.2,
        22.4, 26.6, 20.2, 17.6, 28. , 27. , 34. , 31. , 29. , 27. , 24. ,
        23. , 36. , 37. , 31. , 38. , 36. , 36. , 36. , 34. , 38. , 32. ,
        38. , 25. , 38. , 26. , 22. , 32. , 36. , 27. , 27. , 44. , 32. ,
        28. , 31. ]))

In [48]:
a_df.to_csv('samplex.csv')
df['mpg'].to_csv('sampley.csv')

C:\Users\gowri\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=30)
x_train,x_test,y_train,y_test

(array([[ 12.,   8., 150., ...,   0.,   0.,   0.],
        [ 69.,   8., 160., ...,   0.,   0.,   0.],
        [315.,   4.,  90., ...,   0.,   0.,   0.],
        ...,
        [340.,   4.,  92., ...,   0.,   0.,   0.],
        [ 49.,   4.,  86., ...,   0.,   0.,   0.],
        [ 33.,   6., 100., ...,   0.,   0.,   0.]]),
 array([[302.,   4.,  70., ...,   0.,   0.,   0.],
        [241.,   6.,  97., ...,   0.,   0.,   0.],
        [ 78.,   4.,  87., ...,   0.,   0.,   0.],
        ...,
        [ 81.,   4.,  92., ...,   0.,   0.,   0.],
        [ 68.,   8., 155., ...,   0.,   0.,   0.],
        [261.,   6., 120., ...,   0.,   0.,   0.]]),
 array([15. , 12. , 24.3, 19. , 14. , 12. , 37. , 37.3, 33.5, 31. , 37.2,
        25.5, 28. , 28. , 24. , 20.5, 21. , 14. , 22. , 41.5, 26. , 13. ,
        14. , 12. , 21.6, 20.2, 24. , 18. , 29.8, 14. , 18.5, 32.4, 20. ,
        13. , 32.1, 19.1, 32.3, 26.8, 13. , 15.5, 20.8, 13. , 30.5, 19. ,
        15. , 25. , 18. , 20. , 14. , 14. , 27. , 28. , 33.5, 26.5, 17.5,
        25. , 21.5, 32. , 25.4, 14. , 18. , 23. , 15.5, 24. , 36.4, 38.1,
        14. , 14. , 18.5, 31. , 34.3, 15. , 16. , 29. , 32.7, 28. , 21. ,
        18. , 26. , 13. , 39. , 20.3, 16. , 13. , 17.5, 24.5, 26. , 20.5,
        36. , 35. , 16. , 32.8, 22. , 23.5, 19. , 31.5, 17.5, 11. , 31.8,
        27.4, 24.5, 14. , 19.8, 29. , 16. , 31. , 30. , 40.8, 27. , 33. ,
        26. , 29. , 23. , 18. , 25. , 17. , 13. , 14. , 22. , 34. , 13. ,
        27. , 25. , 16. , 32.9, 39.4, 30. , 13. , 22. , 13. , 20.6, 24. ,
        13. , 22. , 24. , 21. , 16. , 15.5, 19. , 18.1, 36. , 22. , 25.4,
        15. , 31.3, 46.6, 25. , 15. , 16. , 11. , 26. , 21. , 26. , 34. ,
        11. , 15.5, 14. , 30. , 26. , 19.9, 13. , 25. , 10. , 32. , 30.5,
        26.4, 33. , 29. , 27.9, 14. , 20.2, 15. , 38. , 13. , 13. , 27.2,
        18. , 16. , 27. , 30.7, 24. , 37. , 24.2, 33. , 24. , 20. , 17. ,
        23. , 16. , 15. , 23. , 16. , 14. , 27. , 21.5, 23.9, 15. , 22. ,
        26.6, 20. , 33.5, 34.5, 13. , 15. , 19. , 20. , 23.8, 10. , 23. ,
        29.5, 16.5, 36. , 20. , 17. , 21.1, 30. , 18. , 31.6, 23. , 36. ,
        34.7, 15. , 27.2, 22. , 23. , 20.2, 17. , 18. , 44. , 12. , 23.2,
        16. , 26.6, 27.5, 27.2, 34.1, 17.5, 21. , 15.5, 19. , 19. , 15. ,
        32. , 25. , 17.6, 36.1, 18.2, 31. , 31. , 37. , 14. , 34.2, 36. ,
        16.9, 29.9, 18. , 22.5, 40.9, 17. , 19. , 12. , 28. , 25. , 15. ,
        16.5, 28. , 32. , 18. , 25.5, 16.5, 23.9, 32. ,  9. , 21.5, 43.1,
        24. , 35. , 37.7, 30.9, 33.8, 28.4, 13. , 14.5, 31. , 14. , 44.6,
        20. , 13. , 27. , 18. , 18.6, 24. , 27. , 36. , 15. , 25.1, 30. ,
        38. , 36.1, 26. , 16. , 19. , 23.7, 22. , 11. , 31. , 35.7, 14. ,
        19.2, 18. , 23. , 29.5, 28.1, 28.8, 31.5, 18. , 23. , 24. , 16. ,
        14. , 20.2, 18. , 18. , 29. , 22.3, 16.2, 28. , 20. , 26. , 15. ,
        27. , 26. , 26. , 44.3, 24. , 14. , 32.2, 23.6, 39.1, 13. , 17.6,
        31.9, 38. , 20.5, 29. , 27. , 19.4, 19.2, 30. , 29. , 43.4, 19.2,
        19.4, 28. , 21. , 17. , 19. , 33.7, 20. , 30. , 34.1, 25. , 25. ,
        17. , 35.1, 25.8, 23. , 19. ]),
 array([34.5, 22. , 21. , 15. , 29. , 26. , 13. , 18. , 38. , 26. , 18. ,
        22.4, 17.7, 32.4, 25. , 26. , 21. , 28. , 18.5, 20.6, 34.4, 15. ,
        12. , 17.5, 19. , 29.8, 32. , 28. , 13. , 18.1]))

In [50]:
#fit regression model
m=ensemble.GradientBoostingRegressor(
    n_estimators=1000,
    learning_rate=0.1,
    max_depth=6,
    min_samples_leaf=9,
    max_features=0.1,
    loss='huber',
    random_state=0,
)
m.fit(x_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='huber', max_depth=6,
             max_features=0.1, max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=9, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=1000,
             n_iter_no_change=None, presort='auto', random_state=0,
             subsample=1.0, tol=0.0001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [55]:
#save the trained model to a file so wee can use it in other programs
joblib.dump(m,'m/trained_auto_mpg_model.pkl')

['m/trained_auto_mpg_model.pkl']

In [58]:
#find the error rate on the training set
train=mean_absolute_error(y_train, m.predict(x_train))
print("taining set mean absolute error:%4f" % train)
#find the error rate on the test set
test=mean_absolute_error(y_test, m.predict(x_test))
print("test set mean absolute error:%4f"%test)

taining set mean absolute error:1.837652
test set mean absolute error:1.803881

In [42]:
#df=pd.read_csv("auto-mpg.csv")
#the code of missing value replace
missing_values = ["?"]
df = pd.read_csv("auto-mpg.csv", na_values = missing_values)
b=df.fillna(df.mean(0))
b

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.000000,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.000000,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.000000,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.000000,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.000000,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198.000000,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220.000000,4354,9.0,70,1,chevrolet impala
7,14.0,8,440.0,215.000000,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455.0,225.000000,4425,10.0,70,1,pontiac catalina
9,15.0,8,390.0,190.000000,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383.0,170.000000,3563,10.0,70,1,dodge challenger se
11,14.0,8,340.0,160.000000,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400.0,150.000000,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455.0,225.000000,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113.0,95.000000,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198.0,95.000000,2833,15.5,70,1,plymouth duster
16,18.0,6,199.0,97.000000,2774,15.5,70,1,amc hornet
17,21.0,6,200.0,85.000000,2587,16.0,70,1,ford maverick
18,27.0,4,97.0,88.000000,2130,14.5,70,3,datsun pl510
19,26.0,4,97.0,46.000000,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110.0,87.000000,2672,17.5,70,2,peugeot 504
21,24.0,4,107.0,90.000000,2430,14.5,70,2,audi 100 ls
22,25.0,4,104.0,95.000000,2375,17.5,70,2,saab 99e
23,26.0,4,121.0,113.000000,2234,12.5,70,2,bmw 2002
24,21.0,6,199.0,90.000000,2648,15.0,70,1,amc gremlin
25,10.0,8,360.0,215.000000,4615,14.0,70,1,ford f250
26,10.0,8,307.0,200.000000,4376,15.0,70,1,chevy c20
27,11.0,8,318.0,210.000000,4382,13.5,70,1,dodge d200
28,9.0,8,304.0,193.000000,4732,18.5,70,1,hi 1200d
29,27.0,4,97.0,88.000000,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
368,27.0,4,112.0,88.000000,2640,18.6,82,1,chevrolet cavalier wagon
369,34.0,4,112.0,88.000000,2395,18.0,82,1,chevrolet cavalier 2-door
370,31.0,4,112.0,85.000000,2575,16.2,82,1,pontiac j2000 se hatchback
371,29.0,4,135.0,84.000000,2525,16.0,82,1,dodge aries se
372,27.0,4,151.0,90.000000,2735,18.0,82,1,pontiac phoenix
373,24.0,4,140.0,92.000000,2865,16.4,82,1,ford fairmont futura
374,23.0,4,151.0,104.469388,3035,20.5,82,1,amc concord dl
375,36.0,4,105.0,74.000000,1980,15.3,82,2,volkswagen rabbit l
376,37.0,4,91.0,68.000000,2025,18.2,82,3,mazda glc custom l
377,31.0,4,91.0,68.000000,1970,17.6,82,3,mazda glc custom
378,38.0,4,105.0,63.000000,2125,14.7,82,1,plymouth horizon miser
379,36.0,4,98.0,70.000000,2125,17.3,82,1,mercury lynx l
380,36.0,4,120.0,88.000000,2160,14.5,82,3,nissan stanza xe
381,36.0,4,107.0,75.000000,2205,14.5,82,3,honda accord
382,34.0,4,108.0,70.000000,2245,16.9,82,3,toyota corolla
383,38.0,4,91.0,67.000000,1965,15.0,82,3,honda civic
384,32.0,4,91.0,67.000000,1965,15.7,82,3,honda civic (auto)
385,38.0,4,91.0,67.000000,1995,16.2,82,3,datsun 310 gx
386,25.0,6,181.0,110.000000,2945,16.4,82,1,buick century limited
387,38.0,6,262.0,85.000000,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
388,26.0,4,156.0,92.000000,2585,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112.000000,2835,14.7,82,1,ford granada l
390,32.0,4,144.0,96.000000,2665,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84.000000,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90.000000,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86.000000,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.000000,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84.000000,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.000000,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82.000000,2720,19.4,82,1,chevy s-10

In [44]:
b.to_csv('auto_mpg.csv')

In [18]:
a=df['horsepower']
a.fillna(a.mean())

0      130.000000
1      165.000000
2      150.000000
3      150.000000
4      140.000000
5      198.000000
6      220.000000
7      215.000000
8      225.000000
9      190.000000
10     170.000000
11     160.000000
12     150.000000
13     225.000000
14      95.000000
15      95.000000
16      97.000000
17      85.000000
18      88.000000
19      46.000000
20      87.000000
21      90.000000
22      95.000000
23     113.000000
24      90.000000
25     215.000000
26     200.000000
27     210.000000
28     193.000000
29      88.000000
          ...
368     88.000000
369     88.000000
370     85.000000
371     84.000000
372     90.000000
373     92.000000
374    104.469388
375     74.000000
376     68.000000
377     68.000000
378     63.000000
379     70.000000
380     88.000000
381     75.000000
382     70.000000
383     67.000000
384     67.000000
385     67.000000
386    110.000000
387     85.000000
388     92.000000
389    112.000000
390     96.000000
391     84.000000
392     90.000000
393     86.000000
394     52.000000
395     84.000000
396     79.000000
397     82.000000
Name: horsepower, Length: 398, dtype: float64

In [5]:
from pandas import read_csv
dataset = read_csv('auto-mpg.csv', header=None)
print(dataset.describe())

          0    1    2    3     4     5    6    7           8
count   399  399  399  399   399   399  399  399         399
unique  130    6   83   95   352    96   14    4         306
top      13    4   97  150  2130  14.5   73    1  ford pinto
freq     20  204   21   22     4    23   40  249           6